#!/usr/bin/env python3
"""Export bhr_autoencoder.pth parameters for dependency-free C++ inference.

The checkpoint is a trusted PyTorch zip archive. This exporter intentionally
implements only the small subset of pickle globals used by that checkpoint so
that regenerating the C++ parameters does not require torch, numpy, or sklearn.
"""

import argparse
import codecs
import collections
import io
import math
import pickle
import struct
import zipfile


class _TorchStorageType:
    def __init__(self, fmt):
        self.fmt = fmt


class _Storage:
    def __init__(self, values):
        self.values = values


class _Tensor:
    def __init__(self, storage, offset, shape):
        self.shape = tuple(shape)
        size = math.prod(self.shape)
        self.values = storage.values[offset : offset + size]


class _DType:
    def __init__(self, name, *_args):
        self.name = name

    def __setstate__(self, _state):
        pass


class _NDArray:
    def __setstate__(self, state):
        _version, self.shape, dtype, _fortran_order, raw = state
        self.values = _decode_array(dtype, raw)


class _StandardScaler:
    def __setstate__(self, state):
        self.__dict__.update(state)


def _decode_array(dtype, raw):
    fmt = {"f8": "d", "f4": "f", "i8": "q"}[dtype.name]
    item_size = struct.calcsize(fmt)
    return list(struct.unpack("<" + fmt * (len(raw) // item_size), raw))


def _rebuild_tensor(storage, offset, shape, _stride, *_args):
    return _Tensor(storage, offset, shape)


def _scalar(dtype, raw):
    return _decode_array(dtype, raw)[0]


def _reconstruct(*_args):
    return _NDArray()


class _CheckpointUnpickler(pickle.Unpickler):
    def __init__(self, checkpoint, pickle_data, data_prefix):
        super().__init__(pickle_data, encoding="bytes")
        self.checkpoint = checkpoint
        self.data_prefix = data_prefix

    def find_class(self, module, name):
        classes = {
            ("collections", "OrderedDict"): collections.OrderedDict,
            ("torch._utils", "_rebuild_tensor_v2"): _rebuild_tensor,
            ("sklearn.preprocessing._data", "StandardScaler"): _StandardScaler,
            ("numpy._core.multiarray", "scalar"): _scalar,
            ("numpy", "dtype"): _DType,
            ("_codecs", "encode"): codecs.encode,
            ("numpy._core.multiarray", "_reconstruct"): _reconstruct,
            ("numpy", "ndarray"): _NDArray,
        }
        if module == "torch" and name == "FloatStorage":
            return _TorchStorageType("f")
        if module == "torch" and name == "LongStorage":
            return _TorchStorageType("q")
        if (module, name) in classes:
            return classes[(module, name)]
        raise ValueError(f"unsupported checkpoint global: {module}.{name}")

    def persistent_load(self, storage_info):
        _tag, storage_type, key, _location, count = storage_info
        if isinstance(key, bytes):
            key = key.decode()
        raw = self.checkpoint.read(f"{self.data_prefix}data/{key}")
        values = struct.unpack("<" + storage_type.fmt * count, raw)
        return _Storage(list(values))


def _load_checkpoint(path):
    with zipfile.ZipFile(path) as checkpoint:
        pickle_path = next(
            path for path in checkpoint.namelist() if path.endswith("data.pkl")
        )
        prefix = pickle_path[: -len("data.pkl")]
        return _CheckpointUnpickler(
            checkpoint, io.BytesIO(checkpoint.read(pickle_path)), prefix
        ).load()


def _cpp_name(name):
    return name.replace(".", "_")


def _format_float(value):
    formatted = f"{value:.9g}"
    if "." not in formatted and "e" not in formatted:
        formatted += ".0"
    return formatted + "f"


def _format_array(name, values):
    values = [_format_float(value) for value in values]
    rows = ["    " + ", ".join(values[index : index + 6])
            for index in range(0, len(values), 6)]
    return (f"inline constexpr float {name}[] = {{\n" +
            ",\n".join(rows) + "\n};\n")


def export(checkpoint_path, output_path):
    checkpoint = _load_checkpoint(checkpoint_path)
    scaler = checkpoint["scaler"]
    lines = [
        "// Generated by anomaly_detection/export_bhr_model.py.\n",
        "// Do not edit manually; regenerate from anomaly_detection/bhr_autoencoder.pth.\n",
        "#ifndef __MEM_RUBY_NETWORK_GARNET_BHR_AUTOENCODER_PARAMS_HH__\n",
        "#define __MEM_RUBY_NETWORK_GARNET_BHR_AUTOENCODER_PARAMS_HH__\n\n",
        "namespace gem5::ruby::garnet::bhr_model_params\n{\n\n",
        f"inline constexpr float threshold = {_format_float(checkpoint['threshold'])};\n",
        _format_array("scaler_mean", scaler.mean_.values),
        _format_array("scaler_scale", scaler.scale_.values),
    ]
    for name, tensor in checkpoint["model_state"].items():
        if name.endswith("num_batches_tracked"):
            continue
        lines.append(_format_array(_cpp_name(name), tensor.values))
    lines.extend([
        "\n} // namespace gem5::ruby::garnet::bhr_model_params\n\n",
        "#endif // __MEM_RUBY_NETWORK_GARNET_BHR_AUTOENCODER_PARAMS_HH__\n",
    ])
    with open(output_path, "w", encoding="utf-8") as output:
        output.writelines(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("checkpoint")
    parser.add_argument("output")
    args = parser.parse_args()
    export(args.checkpoint, args.output)


if __name__ == "__main__":
    main()
